apiVersion: v1
kind: ConfigMap
metadata:
  name: mini-wms-config
  namespace: mini-wms
data:
  DB_HOST:    "mini-wms-mysql"
  DB_PORT:    "3306"
  DB_NAME:    "mini_wms"
  DB_USER:    "root"
  REDIS_HOST: "mini-wms-redis"
  REDIS_PORT: "6379"
  APP_ENV:    "production"
  LOG_PATH:   "/var/www/html/logs/app.log"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mini-wms-nginx-config
  namespace: mini-wms
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        root  /var/www/html/public;
        index index.php;

        add_header X-Frame-Options         "DENY"                            always;
        add_header X-Content-Type-Options  "nosniff"                         always;
        add_header Referrer-Policy         "strict-origin-when-cross-origin" always;

        gzip on;
        gzip_types text/plain text/css application/json application/javascript;

        location ~* \.(css|js|png|jpg|gif|ico|svg|woff|woff2)$ {
            expires 30d;
            add_header Cache-Control "public, immutable";
            try_files $uri =404;
            access_log off;
        }

        location ~ /\. { deny all; }

        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass   mini-wms-app:9000;
            fastcgi_index  index.php;
            include        fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param  PATH_INFO       $fastcgi_path_info;
            fastcgi_read_timeout  300;
        }
    }
